version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    executor:
      name: node/default
      tag: '10.21.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn test

workflows:
  test:
    jobs:
      - test
